name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Install CloudBase-Cli
        run: npm install -g @cloudbase/cli

      - name: Login to Tencent CloudBase
        env:
          SECRET_ID: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
        run: tcb login --apiKeyId "$SECRET_ID" --apiKey "$SECRET_KEY"

      - name: Deploy to Tencent CloudBase
        env:
          ENV_ID: ${{ secrets.TENCENT_CLOUD_ENV_ID }}
        run: tcb hosting deploy ./public -e "$ENV_ID" 
